name: CI_tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: macos-26-xlarge

    timeout-minutes: 8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.0.1.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Run tests for iOS
        run: |
          xcodebuild clean build test -scheme DMUnLoader -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 17 Pro,OS=26.0.1" -enableThreadSanitizer YES